# Default values for cbi-oi-kubecost-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: public.ecr.aws/flexera/cbi-oi-kubecost-exporter
  pullPolicy: Always
  tag: "1.24"

imagePullSecrets: []

persistentVolume:
  # -- Persistent Volume size.
  size: 1Gi
  # -- Enable Persistent Volume. Recommended setting is true to prevent loss of historical data.
  enabled: true

# -- Setting up a cronJob scheduler to run an export task at the desired time.
cronSchedule: "0 */24 * * *" # every 24 hours

# -- The maximum duration in seconds for the cron job to complete
activeDeadlineSeconds: 10800 # 3 hour

flexera:
  # -- The refresh token used to obtain an access token for the Flexera One API. Please refer to [Generating a Refresh Token](https://docs.flexera.com/flexera/EN/FlexeraAPI/GenerateRefreshToken.htm) in the Flexera documentation.
  # You can provide the refresh token in two ways:
  # 1. Directly as a string:
  #    refreshToken: "your_token_here"
  # 2. Reference it from a Kubernetes secret:
  #    refreshToken:
  #      valueFrom:
  #        secretKeyRef:
  #          name: flexera-secrets  # Name of the Kubernetes secret
  #          key: refresh_token     # Key in the secret containing the refresh token
  refreshToken: ""
  # -- The service account client ID used to obtain an access token for the Flexera One API. Please refer to [Using a Service Account](https://docs.flexera.com/flexera/EN/FlexeraAPI/ServiceAccounts.htm?Highlight=service%20account) in the Flexera documentation. This parameter is incompatible with **refreshToken**, use only one of them.
  serviceAppClientId: ""
  # -- The service account client secret used to obtain an access token for the Flexera One API. Please refer to [Using a Service Account](https://docs.flexera.com/flexera/EN/FlexeraAPI/ServiceAccounts.htm?Highlight=service%20account) in the Flexera documentation. This parameter is incompatible with **refreshToken**, use only one of them.
  serviceAppClientSecret: ""
  # -- The ID of your Flexera One organization, please refer to [Organization ID Unique Identifier](https://docs.flexera.com/flexera/EN/FlexeraAPI/APIKeyConcepts.htm#gettingstarted_2697534192_1120261) in the Flexera documentation.
  orgId: ""
  # -- The ID of the bill connect to which to upload the data. To learn more about Bill Connect, and how to obtain your BILL_CONNECT_ID, please refer to [Creating Kubecost CBI Bill Connect](https://docs.flexera.com/flexera/EN/Optima/CreateKubecostBillConnect.htm) in the Flexera documentation.
  billConnectId: "cbi-oi-kubecost-1"
  # -- The zone of your Flexera One account. Valid values are NAM, EU or AU.
  shard: "NAM"
  # -- Flag to enable automatic creation of Bill Connect.
  createBillConnectIfNotExist: "false"
  # -- Vendor name for the Bill Connect. It is used when CREATE_BILL_CONNECT_IF_NOT_EXIST is set to true.
  vendorName: "Kubecost"
  # -- Flag to allow overriding the podlabels with namespace labels
  overridePodLabels: "true"

kubecost:
  # -- Default kubecost-cost-analyzer service host on the current cluster. For current cluster is serviceName.namespaceName.svc.cluster.local
  host: "kubecost-cost-analyzer.kubecost.svc.cluster.local:9090"
  # -- The base path for the Kubecost API endpoint.
  apiPath: "/model/"
  # -- Indicates the host to use to obtain the Kubecost configuration. This is an optional configuration, if not configured, the same host value used for the allocation API is used.
  configHost: ""
  # -- The base path to get the kubecost configuration. This is an optional configuration, if not configured, the same api path value used for the allocation API is used.
  configApiPath: ""
  # -- The level of granularity to use when aggregating the cost data. Valid values are namespace, controller, node, or pod.
  aggregation: "pod"
  # -- Comma-separated list of namespaces to share costs with the remaining non-idle, unshared allocations.
  shareNamespaces: "kube-system,cadvisor"
  # -- Indicates whether to include cost of idle resources.
  idle: true
  # -- Indicates whether idle allocations are created on a per node basis.
  idleByNode: false
  # -- Indicates whether allocate idle cost proportionally across non-idle resources.
  shareIdle: false
  # -- Indicates whether to share the cost of cluster overhead assets across tenants of those resources.
  shareTenancyCosts: true
  # -- Optional multiplier for costs.
  multiplier: 1.0
  # -- Indicates the pagination limit
  pageSize: 500

# -- Indicates whether to delete files generated for previous months. Note: current and previous months data is kept.
fileRotation: true

# -- File path to mount persistent volume.
filePath: "/var/kubecost"

# -- Indicates whether to collect and export previous month data. Default is true. Setting this flag to false will prevent collecting and uploading the data from previous month and only upload data for the current month. Partial Data (i.e. missing data for some days) for previous month will not be uploaded even if the flag value is set to true.
includePreviousMonth: true

# -- Indicates the timeout per each request in minutes.
requestTimeout: 5

# -- Indicates the default currency to use in case something fails while getting the currency from the kubecost configuration.
defaultCurrency: "USD"

# -- Pod environment variables.
# Example using envs to use proxy:
# {"NO_PROXY": ".svc,.cluster.local", "HTTP_PROXY": "http://proxy.example.com:80", "HTTPS_PROXY": "http://proxy.example.com:80"}
env: {}
