# Default values for cbi-oi-kubecost-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: public.ecr.aws/flexera/cbi-oi-kubecost-exporter
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

persistentVolume:
  # -- Persistent Volume size
  size: 1Gi
  # -- Enable Persistent Volume. If this setting is disabled, it may lead to inability to store history and data uploads older than 15 days in Flexera One
  enabled: true

# -- Setting up a cronJob scheduler to run an export task at the right time
cronSchedule: "0 */6 * * *" # every 6 hours

flexera:
  # -- Refresh Token from FlexeraOne
  # You can provide the refresh token in two ways:
  # 1. Directly as a string:
  #    refreshToken: "your_token_here"
  # 2. Reference it from a Kubernetes secret:
  #    refreshToken:
  #      valueFrom:
  #        secretKeyRef:
  #          name: flexera-secrets  # Name of the Kubernetes secret
  #          key: refresh_token     # Key in the secret containing the refresh token
  refreshToken: ""
  # -- Flexera Organization ID
  orgId: ""
  # -- Bill Connect ID
  billConnectId: "cbi-oi-kubecost-1"
  # -- Shard ("NAM", "EU", "AU")
  shard: "NAM"

kubecost:
  # -- Default kubecost-cost-analyzer service host on the current cluster. For current cluster is serviceName.namespaceName.svc.cluster.local
  host: "kubecost-cost-analyzer.kubecost.svc.cluster.local:9090"
  # -- Base path for the Kubecost API endpoints
  apiPath: "/model/"
  # -- Aggregation Level ("namespace", "controller", "pod")
  aggregation: "pod"
  # -- Comma-separated list of namespaces to share costs
  shareNamespaces: "kube-system,cadvisor"
  # -- Include cost of idle resources
  idle: true
  # -- Allocate idle cost proportionally
  shareIdle: false
  # -- Share the cost of cluster overhead assets such as cluster management costs
  shareTenancyCosts: true
  # -- Cost multiplier
  multiplier: 1.0

# -- Delete files generated for the previous month (or the month before the previous month if ALLOW_PREVIOUS_MONTH is set to true)
fileRotation: true

# -- Filepath to mount persistent volume
filePath: "/var/kubecost"

# -- Allow export of data from previous month
allowPreviousMonth: false
