{{- if .Values.persistentVolume -}}
{{- if .Values.persistentVolume.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cbi-oi-kubecost-exporter.fullname" . }}
  labels:
    {{ include "cbi-oi-kubecost-exporter.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistentVolume.storageClass }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  {{ end }}
  resources:
    requests:
    {{- if .Values.persistentVolume }}
      storage: {{ .Values.persistentVolume.size }}
    {{- else }}
      storage: 0.2Gi
    {{ end }}
{{- end -}}
{{- else -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cbi-oi-kubecost-exporter.fullname" . }}
  labels:
    {{ include "cbi-oi-kubecost-exporter.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistentVolume.storageClass }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  {{ end }}
  resources:
    requests:
    {{- if .Values.persistentVolume }}
      storage: {{ .Values.persistentVolume.size }}
    {{- else }}
      storage: 0.2Gi
    {{ end }}
{{- end -}}