name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - "test-*"
    tags:
      - "release-*"
      - "test-*"
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Extract version from Chart.yaml or git tag
        id: extract_version
        run: |
          if [[ "${{ github.event_name }}" == "push" && -z "${{ github.event.release }}" ]]; then
            VERSION=$(grep 'appVersion:' ./helm-chart/Chart.yaml | awk '{print $$2}' | tr -d '"')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            VERSION=$(echo ${GITHUB_REF#refs/tags/})
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::479353902725:role/gha-flexera-public-cbi-oi-kubecost-exporter-push
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
          registries: public.ecr.aws/flexera

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            public.ecr.aws/flexera/cbi-oi-kubecost-exporter:${{ steps.extract_version.outputs.version }}
            ${{ (github.ref == 'refs/heads/main') && 'public.ecr.aws/flexera/cbi-oi-kubecost-exporter:latest' || '' }}
