name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::479353902725:role/gha-flexera-public-cbi-oi-kubecost-push
          aws-region: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: public.ecr.aws/flexera/cbi-oi-kubecost-exporter:${{ github.sha }}

      - name: Update Helm chart
        run: |
          sed -i "s|repository:.*|repository: public.ecr.aws/flexera/cbi-oi-kubecost-exporter|" helm-chart/values.yaml
          sed -i "s|tag:.*|tag: ${{ github.sha }}|" helm-chart/values.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add helm-chart/values.yaml
          git commit -m "Update Helm chart with new image tag [skip ci]"
          git push
